name: compilation and PDF generation

on: push

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: compile project
        run: dotnet build --no-restore

  pdf-generation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: BaileyJM02/markdown-to-pdf@v1
        with:
          input_dir: docs
          output_dir: pdfs
          build_html: true
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: pdfs
        
      
